---
# tasks file for add_NodeExporter
- name: Create node prometheus config dir
  file:
    path: "{{ prometheus_dir_configuration }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: Create node prometheus bin dir
  file:
    path: "{{ prometheus_bin }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

# - name: if node prometheus exist get version
#   shell: "cat /etc/systemd/system/prometheus.service | grep Version | sed s/'.*Version '//g"
#   when: __check_prometheus_present.stat.exists == true
#   changed_when: false
#   register: __get_prometheus_version

- name: Download and unzip node prometheus if not exist
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: Move the binary to the final destination
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus/prometheus"
    dest: "{{ prometheus_bin }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
    remote_src: yes
- name: Move the config file to the final destination
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus/prometheus.yaml"
    dest: "{{ prometheus_dir_configuration }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
    remote_src: yes
  #when: __check_prometheus_present.stat.exists == false or not __get_prometheus_version.stdout == prometheus_version

- name: Clean
  file:
    path: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/
    state: absent

- name: Add prometheus port to firewall
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled

- name: Install service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0744
  notify: start_prometheus

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus
  
- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes